INSERT INTO public.specialization (name) VALUES
  ('Informatyka'),
  ('Automatyka i Robotyka'),
  ('Teleinformatyka'),
  ('Inżynieria Biomedyczna'),
  ('Mikroelektronika w Technice i Medycynie'),
  ('Budownictwo'),
  ('Górnictwo i Geologia'),
  ('Inżynieria środowiska'),
  ('Zarządzanie i Inżynieria Produkcji'),
  ('Rewitalizacja Terenów Zdegradowanych'),
  ('Metalurgia'),
  ('Inżynieria Materiałowa'),
  ('Informatyka Stosowana'),
  ('Inżynieria Obliczeniowa'),
  ('Inżynieria Ciepła'),
  ('Edukacja Techniczno-Informatyczna'),
  ('Elektronika'),
  ('Elektronika i Telekomunikacja'),
  ('Mechanika i Budowa Maszyn'),
  ('Inżynieria Mechatroniczna'),
  ('Inżynieria Akustyczna'),
  ('Inżynieria Mechaniczna i Materiałowa'),
  ('Geofizyka'),
  ('Ekologiczne Źródła Energii'),
  ('Geoinformatyka'),
  ('Turystyka i Rekreacja'),
  ('Ochrona Środowiska'),
  ('Geodezja i Kartografia'),
  ('Geoinformacja'),
  ('Technologia Chemiczna'),
  ('Ceramika'),
  ('Chemia Budowlana'),
  ('Inżynieria Procesów Odlewniczych'),
  ('Komputerowe Wspomaganie Procesów Inżynierskich'),
  ('Inżynieria Naftowa i Gazownicza'),
  ('Zarządzanie'),
  ('Informatyka i Ekonometria'),
  ('Elektrotechnika'),
  ('Energetyka'),
  ('Energetyka Odnawialna i Zarządzanie Energią'),
  ('Fizyka Medyczna'),
  ('Fizyka Techniczna'),
  ('Matematyka'),
  ('Kulturoznawstwo'),
  ('Socjologia'),
  ('Informatyka Społeczna'),
  ('Elektromechanika'),
  ('Cyberbezpieczeństwo'),
  ('Telekomunikacja'),
  ('Electronic and Computer Engineering'),
  ('Architektura'),
  ('Gospodarka Przestrzenna'),
  ('Biotechnologia'),
  ('Inżynieria chemiczna i procesowa'),
  ('Chemia i analityka przemysłowa'),
  ('Mechatronika'),
  ('Technologie Ochrony Środowiska'),
  ('Inżynieria Systemów'),
  ('Inżynieria zarządzania'),
  ('Transport'),
  ('Fizyka techniczna'),
  ('Inżynieria Kwantowa'),
  ('Optyka'),
  ('Matematyka Stosowana'),
  ('Matematyka i Statystyka'),
  ('Informatyka Przemysłowa'),
  ('Mechatronika Pojazdów'),
  ('Inżynieria Odnawialnych Źródeł Energii'),
  ('Budowa Maszyn i Pojazdów');


INSERT INTO public.country (name) VALUES
  ('Poland');

INSERT INTO public.university (name,id_country) VALUES
  ('Akademia Górniczo-Hutnicza',1),
  ('Politechnika Wrocławska',1);

INSERT INTO public.faculty (name,id_university) VALUES
  ('Wydział Górnictwa i Geoinżynierii',1),
  ('Wydział Inżynierii Metali i Informatyki Przemysłowej',1),
  ('Wydział Elektrotechniki, Automatyki, Informatyki i Inżynierii Biomedycznej',1),
  ('Wydział Informatyki, Elektroniki i Telekomunikacji',1),
  ('Wydział Inżynierii Mechanicznej i Robotyki',1),
  ('Wydział Geologii, Geofizyki i Ochrony Środowiska',1),
  ('Wydział Geodezji Górniczej i Ochrony Środowiska',1),
  ('Wydział Inżynierii Meteriałowej i Ceramiki',1),
  ('Wydział Odlewnictwa',1),
  ('Wydział Metali Nieżelaznych',1),
  ('Wydział Wiertnictwa, Nafty i Gazu',1),
  ('Wydział Zarządzania',1),
  ('Wydział Energetyki i Paliw',1),
  ('Wydział Fizyki i Informatyki Stosowanej',1),
  ('Wydział Matematyki Stosowanej',1),
  ('Wydział Humanistyczny',1),
  ('Wydział Architektury',2),
  ('Wydział Budownictwa Lądowego i Wodnego',2),
  ('Wydział Chemiczny',2),
  ('Wydział Elektroniki',2),
  ('Wydział Elektryczny',2),
  ('Wydział Geoinżynierii, Górnictwa i Geologii',2),
  ('Wydział Inżynierii Środowiska',2),
  ('Wydział Informatyki i Zarządzania',2),
  ('Wydział Mechaniczno-Energetyczny',2),
  ('Wydział Mechaniczny',2),
  ('Wydział Podstawowych Problemów Techniki',2),
  ('Wydział Elektroniki Mikrosystemów i Fotoniki',2),
  ('Wydział Matematyki',2),
  ('Wydział Techniczno-Informatyczny',2),
  ('Wydział Techniczno-Inżynieryjny',2),
  ('Wydział Techniczno-Przyrodniczy',2);

INSERT INTO public.faculty_specialization (id_faculty,id_specialization) VALUES
  (1,6),
  (1,7),
  (1,8),
  (1,9),
  (1,10),
  (2,11),
  (2,12),
  (2,13),
  (2,14),
  (2,15),
  (2,16),
  (3,1),
  (3,2),
  (3,4),
  (3,5),
  (3,38),
  (4,17),
  (4,18),
  (4,1),
  (4,3),
  (5,19),
  (5,20),
  (5,21),
  (5,22),
  (5,2),
  (6,23),
  (6,24),
  (6,25),
  (6,26),
  (6,27),
  (6,7),
  (6,13),
  (6,8),
  (7,28),
  (7,29),
  (7,8),
  (8,30),
  (8,31),
  (8,32),
  (8,12),
  (9,33),
  (9,34),
  (10,11),
  (10,12),
  (10,9),
  (11,7),
  (11,35),
  (12,36),
  (12,37),
  (12,9),
  (13,30),
  (13,39),
  (13,40),
  (14,41),
  (14,42),
  (14,13),
  (15,43),
  (16,44),
  (16,45),
  (16,46),
  (17,51),
  (17,52),
  (18,6),
  (19,53),
  (19,54),
  (19,55),
  (19,12),
  (19,30),
  (20,1),
  (20,2),
  (20,3),
  (20,17),
  (20,48),
  (20,49),
  (20,50),
  (21,2),
  (21,38),
  (21,56),
  (22,7),
  (22,28),
  (23,8),
  (23,57),
  (24,1),
  (24,58),
  (24,59),
  (25,19),
  (25,39),
  (26,19),
  (26,2),
  (26,56),
  (26,9),
  (26,60),
  (26,4),
  (27,4),
  (27,1),
  (27,61),
  (27,62),
  (27,63),
  (28,18),
  (28,56),
  (29,64),
  (29,65),
  (29,43),
  (30,66),
  (31,67),
  (32,68),
  (32,69);


INSERT INTO public.link (address) VALUES
  ('https://www.postgresql.org/docs/9.1/static/datatype-character.html'),
  ('http://www.blindtextgenerator.com/lorem-ipsum'),
  ('https://www.meetspaceapp.com/2016/04/12/passwords-postgresql-pgcrypto.html'),
  ('https://spring.io/guides/gs/spring-boot/'),
  ('https://www.baeldung.com/spring-security-oauth-jwt'),
  ('https://shareurcodes.com/blog/best%20way%20to%20store%20password%20in%20database%202017%20edition'),
  ('https://www.quora.com/What-is-the-most-reliable-safe-and-efficient-password-hashing-algorithm-as-of-2018'),
  ('https://howtodoinjava.com/security/how-to-generate-secure-password-hash-md5-sha-pbkdf2-bcrypt-examples/');


INSERT INTO public.tag (name) VALUES
  ('IT'),
  ('Docker'),
  ('Java'),
  ('Spring'),
  ('JavaScript'),
  ('Angular'),
  ('React'),
  ('Machine learning'),
  ('Hashing'),
  ('Security'),
  ('Database'),
  ('Postgres'),
  ('MySQL'),
  ('Python'),
  ('Go'),
  ('Mechanical'),
  ('Thermovision'),
  ('Welding'),
  ('Bearing'),
  ('3D Modeling'),
  ('Engine'),
  ('Motorization'),
  ('Dynamics'),
  ('Hydrostatics'),
  ('Heat flow'),
  ('Catalyst'),
  ('Production line'),
  ('Electronics'),
  ('Gear'),
  ('Cryogenics'),
  ('Biology'),
  ('Veterinary medicine'),
  ('Humans'),
  ('Animals'),
  ('Bacteria'),
  ('Virus'),
  ('Medicine'),
  ('DNA'),
  ('Cells'),
  ('Climate changes'),
  ('Cancer'),
  ('Hormones'),
  ('Nutrition'),
  ('Chromosome'),
  ('Metabolism');


INSERT INTO public.user (name,surname,password,email,id_university,id_faculty,id_specialization,image_url,sex) VALUES
  ('Andrzej','Programista','$2a$12$KClYt/aT06q.YvjuTQk3JexiUYnZYprVcWZZIZ4SRy9mtCCLKy1CO','test@gmail.com',1,3,1,'https://www.szerokikadr.pl/public/repozytorium/poradnik/201211/3/160_732388c2.jpg','male'),
  ('Paweł','Mechaniczny','$2a$12$qtoJ6o22zngKhlIvUCv1EeXzvtQa2LFaxziv97rL8CRGmmo1OwbPG','test1@gmail.com',1,3,1,'http://bi.gazeta.pl/im/6e/1a/13/z20031086V,Zoo-w-Lodzi-niedawno-swietowalo-narodziny-w-rodzin.jpg','male'),
  ('Kamila','Biologiczna','$2a$12$tyoHAQW3UotiFXCPD74Kh.ZlHxUtbu8AkaMkzDtIBC46NyOfFRHzy','test2@gmail.com',1,3,1,'https://ocdn.eu/pulscms-transforms/1/m6nktkpTURBXy8wZjc0MzMzMmFmNzg5YjExNjE2NzE0ZWQyODA4MWI0Yi5qcGeRkwLNAyYA','male'),
  ('Ola','Zegarek','$2a$12$w8pSf4F4tX5ZpcHZiwggSu6j6MVmirQJT6u1vipsAtzTGdj.nLEaS','test3@gmail.com',1,3,1,'http://t-eska.cdn.smcloud.net/regionalna/t/2/t/image/1c62fcdad261b54757dd160d126afdf1RAtQqTIl-lama.jpg/ru-0-r-660,660-q-80-n-1c62fcdad261b54757dd160d126afdf1RAtQqTIllama.jpg','male'),
  ('Ala','Konieczny','$2a$12$5xVLJm5PI6Lf.uWyaPSp4.F6KXT7WpdSPZ.lXUUT5FsinMuAcf6ee','test4@gmail.com',1,3,2,'https://i2.wp.com/fotozin.pl/wp-content/uploads/2017/02/andreas_gursky_Rhine_II.jpg?resize=750%2C500&ssl=1','male'),
  ('Marek','Bis','$2a$12$lcKm.B8EHa6VpYfinW.Gu.gvzeMlljC28kVoGiQQGXM.d54TOacnC','test5@gmail.com',1,1,6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcThY9PivBG8zpTa4YfB5QlnO7N-ykrqNjl6AjMiy8VOgLP2gZww','female'),
  ('Marcin','Grabarz','$2a$12$.TWN5vXmgLOn40r3dLbTJ.dnF1q9SuM0bA0VuDh3we8mbyjgGsF0u','test6@gmail.com',1,1,7,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsTwpUfPyh6j4HQKvUHmoQ-IgC_9BEjkQBsaZ4MvA5CnwKYrVHjg','female'),
  ('Iza','Ptak','$2a$12$VYmI2II1vRb9S7DcTknRk.IBVc090e.7biIsJZnd8czHpBXOL.awe','test7@gmail.com',1,1,8,'http://lesnikmlynary.pl/files/gallery/1/5036-zdjecie-glowne-48-piekno-lowiectwa-6.jpg?1444338551','female'),
  ('Mateusz','Kołodziej','$2a$12$GWiD8S1pdG5hCaXoqr7Uw.5K/V5YOplGYv2wjFEy1MkdxYgnI78aC','test8@gmail.com',1,3,2,'http://www.koszatniczki.pl/wp-content/uploads/2017/03/zdjecie-11.jpg','female'),
  ('Zofia','Falka','$2a$12$qMikQ4Wk1i3RSD9.KFSgjOIgcXLc1pvW6GznoO1fB6lyW8FdPlQMG','test9@gmail.com',1,3,1,'https://eloblog.pl/wp-content/uploads/2015/10/Monkey-selfie.jpg','female');


INSERT INTO public.project (name,description,image_url,public) VALUES
  ('Project Titan','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://www.simplilearn.com/ice9/free_resources_article_thumb/Project-Scope-Management-Cover.jpg',TRUE),
  ('Search engine','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure? On the other hand, we denounce with righteous indigna','https://cdn.lynda.com/course/506926/506926-636238695730179167-16x9.jpg',TRUE),
  ('Electric car','Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues. It va esser tam simplic quam Occidental in fact, it va esser Occidental. A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es. Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronuncia','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHzbFfkfTT7x42-kR5KNhkL8d9F8Awzyb1gyfLpRGrBbNQ0M2kHg',TRUE),
  ('Online board game','The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the','https://4.bp.blogspot.com/-D6ltBI2Xc-U/UnywrCXS7cI/AAAAAAAACA8/FCZ9almgczE/s1600/18+Database+Projects.png',TRUE),
  ('Manhattan Project','Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Al','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhRngfwnjckXUWgAjeTaJbKQcTwgQW70c_7Ef5QCgi0gz-xfSP',TRUE),
  ('Chatbot','A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almig','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAT-OrwbWuW0GCK7jDRC2dOZ_nmtCoThT43tyAq2VjC5r-mWGv',TRUE),
  ('Cloud Platform','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV6AIE4NmNhYREIFG6KwkHbhdk6yPVakhJ-8j9enOymyf0_BfB',TRUE),
  ('Car traffic monitoring','The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave ghost pled. Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W. zaps Iraq. Cozy sphinx waves quart jug of bad milk. A very bad quack might jinx zippy fowls. Few quips galvanized the mock jury box. Quick brown dogs jump over the lazy fox. The jay, pig, fox, zebra, and my wolves quack! Blowzy red vixens fight for a quick jump. Joaquin Phoenix was gazed by MTV for luck. A wizard’s job is to vex chumps quickly in fog. Watch "Jeopardy!", Alex Trebeks.','https://pbs.twimg.com/profile_images/955243107901042690/94be1jHm_400x400.jpg',TRUE),
  ('Platformer game on Unity','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSHPye9CoL5kMw8Gy53b_soHHcLG4Cp3ahmvSfoYa9hP_qPQAH',TRUE),
  ('Emotions recognition','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://kpbs.media.clients.ellingtoncms.com/img/news/tease/2016/01/08/Faces-EmotionsSmall.jpeg',TRUE),
  ('Car Prototype','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://car-images.bauersecure.com/pagefiles/9187/06_hondansx-starburst.jpg',TRUE),
  ('Pressure tank','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','http://chemet.com.pl/resources/gallery/menu_glowne/6536-zbiorniki-kriogeniczne-8-jpg-1920-1280.jpg',TRUE),
  ('New generation battery','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://ehu.eus/documents/10136/8554469/web_Baterias+de+sodio+ion-TXSZTlsX.jpg/82288645-5b11-d351-25b8-2313a8595ed0?t=1516354806000',TRUE),
  ('Cash register','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://images-na.ssl-images-amazon.com/images/I/91wKQ3F9otL._SL1500_.jpg',TRUE),
  ('Freight wagons','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://i.ytimg.com/vi/RkoQHmSSUSg/maxresdefault.jpg',TRUE),
  ('Electric skateboard','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://d23x084dcxncv3.cloudfront.net/skatehut/product/be8c06de.LOU%203.0%20Electric%20Skateboard%20-%20Red.jpg/750x750.fit.LOU%203.0%20Electric%20Skateboard%20-%20Red.jpg',TRUE),
  ('Flying drone','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://i2.wp.com/geoawesomeness.com/wp-content/uploads/2017/05/Drone.jpg',TRUE),
  ('Hydroelectric power plant','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://etimg.etb2bimg.com/photo/66280260.cms',TRUE),
  ('Space rocket','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://spacenews.com/wp-content/uploads/2018/04/Omega_in_Flight-879x485.jpg',TRUE),
  ('Modern mechanical buttons','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://i.kinja-img.com/gawker-media/image/upload/s--77gAJxXk--/c_scale,f_auto,fl_progressive,q_80,w_800/18pqaivkrvqaejpg.jpg',TRUE),
  ('Cure for cancer','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://questfusion.com/wp-content/uploads/2016/04/cure-cancer.jpg',TRUE),
  ('Suplementation','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://www.lisagoldbergnutrition.com/wp-content/uploads/2017/12/supplementation-1.jpeg',TRUE),
  ('Genetic experiment','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://image.freepik.com/free-vector/dna-experiments-illustration-of-technology-for-medicine-genetic-research-and-gene-microbiology_33099-453.jpg',TRUE),
  ('Tick preparation','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://molecule8.com/wp-content/uploads/2017/08/ticklogo.jpg',TRUE),
  ('Antibacterial gel','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://www.qualitylogoproducts.com/germs-sanitization/compact-hand-sanitizer-antibacterial-gel05oz-superextralarge.jpg',TRUE),
  ('Genetically modified tree','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','http://blogs.discovermagazine.com/crux/files/2018/04/cristina-gottardi-177261-unsplash.jpg',TRUE),
  ('Drug for hypertension','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/08/blood-796x419.png',TRUE),
  ('Sheep cloning','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://3c1703fe8d.site.internapcdn.net/newman/gfx/news/hires/2017/morelessonsf.png',TRUE),
  ('Horse performance booster','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://saywhat.news/wp-content/uploads/2018/10/img12-5.jpg',TRUE),
  ('Bee protection','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit ve','https://media.boingboing.net/wp-content/uploads/2018/09/bees.jpg',TRUE);

INSERT INTO public.project_link (id_project,id_link) VALUES
  (1,3),
  (1,5),
  (1,7),
  (2,1),
  (2,2),
  (3,7),
  (3,4),
  (3,5),
  (4,6),
  (4,5),
  (5,8),
  (6,1),
  (7,7),
  (8,4),
  (9,6);



INSERT INTO public.project_user (id_project,id_user) VALUES
  (1,1),
  (2,2),
  (3,3),
  (4,4),
  (5,5),
  (6,6),
  (7,7),
  (8,8),
  (9,9),
  (2,1),
  (3,1);

INSERT INTO public.observable (id_project,id_user) VALUES
  (1,1),
  (3,1),
  (5,1),
  (7,1),
  (9,1),
  (12,2),
  (15,2),
  (16,2),
  (19,2),
  (20,2),
  (23,3),
  (25,3),
  (30,3),
  (29,3),
  (27,3);

INSERT INTO public.project_tag (id_project,id_tag) VALUES
  (1,1),
  (1,3),
  (1,6),
  (1,4),
  (2,8),
  (2,15),
  (2,2),
  (2,11),
  (3,1),
  (3,10),
  (3,8),
  (4,5),
  (4,7),
  (4,11),
  (4,13),
  (5,12),
  (5,2),
  (5,9),
  (5,11),
  (6,8),
  (6,7),
  (6,13),
  (6,5),
  (7,2),
  (7,1),
  (7,11),
  (7,9),
  (8,3),
  (8,1),
  (8,15),
  (8,4),
  (9,4),
  (9,3),
  (9,5),
  (9,6),
  (10,10),
  (10,9),
  (10,14),
  (10,8),
  (11,16),
  (11,22),
  (11,21),
  (11,26),
  (12,19),
  (12,16),
  (12,17),
  (12,30),
  (13,25),
  (13,23),
  (13,28),
  (14,20),
  (14,27),
  (14,29),
  (15,18),
  (15,19),
  (15,26),
  (15,21),
  (16,17),
  (16,20),
  (16,25),
  (16,23),
  (17,16),
  (17,29),
  (17,28),
  (18,24),
  (18,17),
  (18,26),
  (19,24),
  (19,22),
  (19,30),
  (19,19),
  (19,18),
  (20,20),
  (20,23),
  (20,28),
  (21,41),
  (21,33),
  (21,31),
  (21,37),
  (22,43),
  (22,45),
  (22,33),
  (22,42),
  (23,38),
  (23,39),
  (23,44),
  (24,34),
  (24,35),
  (24,37),
  (24,36),
  (25,35),
  (25,36),
  (25,33),
  (26,31),
  (26,38),
  (26,40),
  (26,39),
  (27,37),
  (27,33),
  (27,43),
  (28,32),
  (28,34),
  (28,41),
  (28,42),
  (28,44),
  (29,32),
  (29,34),
  (29,41),
  (29,45),
  (30,34),
  (30,32),
  (30,40);

INSERT INTO public.project_details (id_project,content) VALUES
  (1,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quiss'),
  (1,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia volupta'),
  (1,'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human h'),
  (2,'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe a'),
  (2,'The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyo'),
  (3,'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by thei'),
  (3,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy'),
  (3,'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches'),
  (4,'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt'),
  (4,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis,'),
  (5,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia volupta'),
  (6,'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human h'),
  (7,'Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe a'),
  (8,'The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyo'),
  (9,'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by thei');











